import React from 'react'

const Products = [
    {
    _id:'1',
    name:'Airpods Wireless bluetooth',
    image: './images/airpods.jpg',
    description:'Bluetooth tech lets you connect it with compatible devices',
    brand:'Apple',
    catagory: 'Electronics',
    price:89.99,
    countInStock:10,
    rating: 4.5,
    numReviews:12,
    },
    {
    _id:'2',
    name:'alexa',
    image: './images/alexa.jpg',
    description:'Bluetooth tech lets you connect it with compatible devices',
    brand:'Apple',
    catagory: 'Electronics',
    price:80.99,
    countInStock:10,
    rating: 4.5,
    numReviews:15,
    },
    {
    _id:'3',
    name:'camera',
    image: './images/camera.jpg',
    description:'Bluetooth tech lets you connect it with compatible devices',
    brand:'Apple',
    catagory: 'Electronics',
    price:48,
    countInStock:10,
    rating: 5.5,
    numReviews:11,
    },
    {
    _id:'4',
    name:'mouse',
    image: './images/mouse.jpg',
    description:'Bluetooth tech lets you connect it with compatible devices',
    brand:'Apple',
    catagory: 'Electronics',
    price:900.99,
    countInStock:10,
    rating: 4.5,
    numReviews:12,
    },
    {
    _id:'5',
    name:'phone',
    image: './images/phone.jpg',
    description:'Bluetooth tech lets you connect it with compatible devices',
    brand:'Apple',
    catagory: 'Electronics',
    price:89.99,
    countInStock:10,
    rating: 4.5,
    numReviews:12,
    },
    {
    _id:'6',
    name:'playstation',
    image: './images/playstation.jpg',
    description:'Bluetooth tech lets you connect it with compatible devices',
    brand:'Apple',
    catagory: 'Electronics',
    price:89.99,
    countInStock:10,
    rating: 4.5,
    numReviews:12,
    },
    ];
export default Products